In [38]:
import pandas as pd

df_students = pd.read_csv(r"C:\Users\PRIMO TEK\anaconda3\envs\Tp!_Kdd\Data\Tp1.CSV", sep=";")
df_students["source"] = "CSV"

print("CSV chargé:", df_students.shape)
df_students.head()

CSV chargé: (8, 8)

  school sex  age address  G1  G2  G3 source
0     GP   F   18       U   5   6   6    CSV
1     GP   M   17       U   6   5   6    CSV
2     GP   F   15       U  10  10  10    CSV
3     GP   M   16       R  15  14  15    CSV
4     MS   F   19       U  12  13  12    CSV

In [35]:
import json
import pandas as pd

with open(r"C:\Users\PRIMO TEK\anaconda3\envs\Tp!_Kdd\Data\TP1.json", "r") as f:
    json_data = json.load(f)

df_json = pd.DataFrame(json_data["students"])
df_json["source"] = "JSON"

print("JSON chargé:", df_json.shape)
df_json.head()

JSON chargé: (8, 8)

  school sex  age address  G1  G2  G3 source
0     GP   F   18       U   5   6   6   JSON
1     GP   M   17       U   6   5   6   JSON
2     GP   F   15       U  10  10  10   JSON
3     GP   M   16       R  15  14  15   JSON
4     MS   F   19       U  12  13  12   JSON

In [36]:
import sqlite3
import pandas as pd

# students.db 
conn = sqlite3.connect(r"C:\Users\PRIMO TEK\anaconda3\envs\Tp!_Kdd\Data\students.db")
cursor = conn.cursor()

# 
cursor.execute("""
CREATE TABLE IF NOT EXISTS grades (
    id INTEGER PRIMARY KEY,
    name TEXT,
    score REAL
)
""")

cursor.executemany("INSERT INTO grades (name, score) VALUES (?, ?)", [
    ("Ali",    15.5),
    ("Fatima", 18.0),
    ("Omar",   12.0),
])
conn.commit()
print("la base de donnees")

la base de donnees

In [24]:
df_sql = pd.read_sql("SELECT * FROM grades", conn)
df_sql["source"] = "SQL"
print("SQL chargé:", df_sql.shape)
df_sql.head()

SQL chargé: (6, 4)

   id    name  score source
0   1     Ali   15.5    SQL
1   2  Fatima   18.0    SQL
2   3    Omar   12.0    SQL
3   4     Ali   15.5    SQL
4   5  Fatima   18.0    SQL

In [25]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

url = "https://books.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

books = []
for book in soup.find_all("article", class_="product_pod")[:10]:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    books.append({"title": title, "price": price})

df_scraping = pd.DataFrame(books)
df_scraping["source"] = "Scraping"
print("Scraping réussi:", df_scraping.shape)
df_scraping.head()

Scraping réussi: (10, 3)

                                   title    price    source
0                   A Light in the Attic  Â£51.77  Scraping
1                     Tipping the Velvet  Â£53.74  Scraping
2                             Soumission  Â£50.10  Scraping
3                          Sharp Objects  Â£47.82  Scraping
4  Sapiens: A Brief History of Humankind  Â£54.23  Scraping

In [ ]:
import pandas as pd
import json
import sqlite3
from bs4 import BeautifulSoup
import requests

# 1. CSV 
df_csv = pd.DataFrame({
    "school": ["GP","GP","GP","GP","MS","MS","MS","MS"],
    "sex":    ["F","M","F","M","F","M","F","M"],
    "age":    [18, 17, 15, 16, 19, 20, 17, 18],
    "address":["U","U","U","R","U","R","U","R"],
    "G1":     [5,  6, 10, 15, 12,  8, 14, 11],
    "G2":     [6,  5, 10, 14, 13,  9, 13, 12],
    "G3":     [6,  6, 10, 15, 12, 10, 14, 11]

})
df_csv["source"] = "CSV"

# 2. JSON
with open(r"C:\Users\PRIMO TEK\anaconda3\envs\Tp!_Kdd\Data\TP1.json", "r") as f:
    json_data = json.load(f)
df_json = pd.DataFrame(json_data["students"])
df_json["source"] = "JSON"

# 3. SQL
conn = sqlite3.connect(r"C:\Users\PRIMO TEK\anaconda3\envs\Tp!_Kdd\Data\students.db")
df_sql = pd.read_sql("SELECT * FROM grades", conn)
df_sql["source"] = "SQL"

# 4. Scraping
url = "https://books.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
books = []
for book in soup.find_all("article", class_="product_pod")[:10]:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    books.append({"title": title, "price": price})
df_scraping = pd.DataFrame(books)
df_scraping["source"] = "Scraping"

# 5 Fusion
df_final = pd.concat([df_csv, df_json, df_sql, df_scraping], ignore_index=True)
print("✅ Total:", df_final.shape)
df_final.head()

SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' (3758678559.py, line 8)

SyntaxError: incomplete input (511163407.py, line 8)